"""Per-subject content configs (part 2): Music, Wellbeing, Digital Tech, French, Performing Arts, Science."""

SUBJECTS_2 = {
    "Music": {
        "year": "Year 2", "year_short": "Y2",
        "subject": "Music",
        "lesson_title": "Beat vs rhythm: matching and contrasting",
        "vc_codes": "VC2AMU2P01 \\u00b7 VC2AMU2C01 \\u00b7 VC2AMU2D01",
        "vc_descriptors": "Music elements \\u00b7 Beat \\u00b7 Rhythm \\u00b7 Body percussion",
        "sc_1": "I can keep a steady beat with a clap or tap.",
        "sc_2": "I can clap a 4-beat rhythm pattern back accurately.",
        "sc_3": "I can tell the difference between beat and rhythm.",
        "cue_1": "Beat = steady",
        "cue_2": "Rhythm = pattern",
        "cue_3": "Listen first",
        "equipment_label": "INSTRUMENTS",
        "equipment_1": "Body percussion (own)",
        "equipment_2": "Hand drum (teacher)",
        "equipment_3": "Rhythm sticks (1 pair per student)",
        "equipment_4": "Visual: 4-beat grid on board",
        "equipment_5": "Recording of \\u201CWaltzing Matilda\\u201D (steady beat)",
        "entry_1": "Enter, sit cross-legged in circle.",
        "entry_2": "Sticks placed in front, hands on knees.",
        "entry_3": "Wait for silence before vocal warm-up.",
        "exit_1": "Sticks back in basket. Hands on knees.",
        "exit_2": "Stand quietly when called by year level.",
        "exit_3": "Walk back to class teacher in 2 lines.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 drumbeat = freeze, sticks in lap",
        "signal_2": "2 drumbeats = listen position, hands on knees",
        "signal_practise": "Practise the signal x 3 at start.",
        "phase_1": "1. VOCAL WARM-UP",
        "phase_2": "2. LISTENING + ANALYSIS",
        "phase_3": "3. GROUP PLAY",
        "phase_4": "4. SOLO / SMALL GROUP",
        "phase_5": "5. PERFORMANCE SHARE",
        "phase_label_1": "VOCAL WARM-UP", "phase_label_2": "LISTENING (I do)",
        "phase_label_3": "GROUP PLAY (We do)", "phase_label_4": "SMALL GROUP (You do)",
        "phase_label_5": "PERFORMANCE SHARE",
        "p1_1": "All in circle. Hum the warm-up call (descending 5-note pattern).",
        "p1_2": "Echo back. Repeat with body percussion: pat-pat-clap-clap.",
        "p1_3": "Settle to silent listening posture.",
        "p1_say": "\\u201CMusicians warm up bodies AND ears. Today we feel beat AND rhythm.\\u201D",
        "p2_1": "Play 30-sec of \\u201CWaltzing Matilda\\u201D. Pat steady beat on knees.",
        "p2_2": "Demo: clap the rhythm of the words on top of your steady beat.",
        "p2_3": "Define: Beat = steady. Rhythm = pattern of words/sounds.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Beat = steady \\u00b7 Rhythm = pattern",
        "p3_1": "Whole class taps steady beat. Half clap rhythm of \\u201CTwinkle Twinkle\\u201D over top.",
        "p3_2": "Swap roles. Stop after 4 bars. Discuss what worked.",
        "p3_3": "Praise specific students who held steady beat under rhythm.",
        "p3_say": "\\u201CBeat steady. Rhythm clear. Listen first.\\u201D",
        "p4_1": "Pairs: one keeps beat, one claps a 4-beat rhythm of own choosing.",
        "p4_2": "Swap. Try 2 different rhythms on the same beat.",
        "p4_3": "Teacher confers with 5 priority students.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (just steady beat) \\u00b7 Core (beat + 4-beat rhythm) \\u00b7 Tier 3 (compose 8-beat rhythm)",
        "p5_1": "Sit in circle. Choose 3 pairs to perform.",
        "p5_2": "Audience taps steady beat under their rhythm.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CBeat is steady. Rhythm is pattern. Tomorrow we add high and low pitch.\\u201D",
        "behaviour_1": "Drum signal \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model expectation. Restart with circle posture.",
        "behaviour_3": "Repeat \\u2192 sit out 1 song, re-join.",
        "behaviour_4": "Refusing to clap? Offer drum-monitor or audience role.",
        "rescue_1": "Slower tempo \\u2014 50 bpm",
        "rescue_2": "Beat only, no rhythm overlay",
        "rescue_3": "Body percussion only, no sticks yet",
        "ct_note_1": "Sticks back to music room.",
        "ct_note_2": "Note any students who couldn\\u2019t hold beat.",
        "ct_note_3": "Roll stays with class teacher.",
        "prior_1": "Term 1 covered loud / soft + fast / slow.",
        "prior_2": "Most can keep a steady beat in body percussion.",
        "prior_3": "Some confuse beat and rhythm \\u2014 this is the key clarification.",
        "sequence_summary": "W1 (today) \\u00b7 W2 add high/low pitch \\u00b7 W3 introduce notation \\u00b7 W4 small group composition \\u00b7 W5 class performance",
        "resources_prepared": "Sticks counted into baskets. Speaker tested with Matilda track. 4-beat grid on board.",
        "learning_intention": "We are learning to feel and tell apart beat (steady) and rhythm (pattern).",
        "why_this_matters": "Beat and rhythm are the bedrock of all music. Without this distinction students can\\u2019t read notation, play in time, or compose.",
        "vocab_tier1": "fast, slow, loud, soft, sound",
        "vocab_tier2": "beat, rhythm, pattern, steady, clap, tap",
        "vocab_tier3": "tempo, pulse, syncopation, ostinato",
        "routine_1": "Same entry \\u2192 circle \\u2192 sticks in front \\u2192 vocal warm-up every lesson.",
        "routine_2": "Predictable structure protects listening attention.",
        "self_reg_1": "\\u201CHow do you keep your beat steady when others change?\\u201D",
        "self_reg_2": "\\u201CWhat will you listen for first \\u2014 beat or rhythm?\\u201D",
        "self_reg_3": "\\u201CWhat\\u2019s your strategy if you lose the beat?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we feel beat and rhythm \\u2014 and tell them apart.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Pat steady beat on knees to Matilda.",
        "teach_chunk_2": "Chunk 2 (3 min): Clap rhythm of words on top.",
        "teach_chunk_3": "Chunk 3 (4 min): Define beat / rhythm with the 4-beat grid visual.",
        "worked_example": "(audio + visual exemplar: 4-beat grid with quarter notes for beat row, varied notes for rhythm row \\u2014 teacher claps both layers.)",
        "stem_1": "\\u201CThe beat goes \\u2026\\u201D",
        "stem_2": "\\u201CThe rhythm changes when \\u2026\\u201D",
        "stem_3": "\\u201CI listened for \\u2026 first.\\u201D",
        "cfu_1": "\\u201CHands up if this is BEAT (steady knees) or RHYTHM (clap pattern).\\u201D \\u00b7 Show me steady beat with no clapping.",
        "practice_stem_1": "\\u201CMy beat stayed steady because \\u2026\\u201D",
        "practice_stem_2": "\\u201CMy partner\\u2019s rhythm had \\u2026\\u201D",
        "cfu_2": "Mid-play check: stop everyone. \\u201CThumbs \\u2014 was the beat steady or wandering?\\u201D Adjust.",
        "tier1_task_1": "Steady beat only \\u2014 no rhythm overlay",
        "tier1_task_2": "Body percussion (no sticks)",
        "tier1_task_3": "Audio-led with teacher next to you",
        "tier1_task_4": "Verbal description of beat/rhythm OK",
        "core_task_1": "Beat + 4-beat rhythm together",
        "core_task_2": "Use sticks correctly",
        "core_task_3": "Swap roles within pair",
        "core_task_4": "Use cue words during talk",
        "tier3_task_1": "Compose own 8-beat rhythm",
        "tier3_task_2": "Notate it on the 4-beat grid",
        "tier3_task_3": "Lead the class in performing it",
        "tier3_task_4": "Layer 3 different rhythms in a trio",
        "sc_1_short": "steady beat",
        "sc_2_short": "echoing rhythm",
        "sc_3_short": "beat vs rhythm",
        "metacog_1": "\\u201CWas it harder to keep beat or to clap rhythm? Why?\\u201D",
        "metacog_2": "\\u201CWhat helps you stay steady when others change?\\u201D",
        "metacog_3": "\\u201CWhich cue word did you say in your head?\\u201D",
        "retrieval_plan": "Re-feel beat vs rhythm at the start of every Term 2 music lesson. Re-test in W3 + W6.",
        "eald_1": "Visual cue cards for beat/rhythm", "eald_2": "Sentence stems pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to clapsticks and song traditions", "koorie_2": "Yarn circle reflection", "koorie_3": "Acknowledge community song", "koorie_4": "Strength-based feedback",
        "disability_1": "Soft-grip sticks / sound-reduced room", "disability_2": "Visual beat-keeper light", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Sticks + audio provided", "disadv_2": "No-cost body percussion alternative", "disadv_3": "Predictable rhythm = safety", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Eli",
        "adjustment_eg": "Body percussion only \\u2014 no sticks today",
        "support_eg": "Sit beside teacher; teacher mirrors steady beat",
        "lookfor_1": "Holds steady beat for 8 bars",
        "lookfor_2": "Echoes 4-beat rhythm with accuracy",
        "lookfor_3": "Uses \\u2018beat\\u2019 and \\u2018rhythm\\u2019 correctly in talk",
        "misconception_1": "Calls rhythm \\u2018beat\\u2019 \\u2192 demo two clearly contrasting layers",
        "misconception_2": "Speeds up under rhythm \\u2192 metronome support",
        "misconception_3": "Stops beat when listening \\u2192 \\u201Cyour beat lives in your knees\\u201D anchor",
    },

    "Wellbeing": {
        "year": "Year 1", "year_short": "Y1",
        "subject": "Wellbeing",
        "lesson_title": "Naming feelings using the feelings wheel",
        "vc_codes": "VC2HPER1P01 \\u00b7 VC2HPER1P03 \\u00b7 VC2HPER1S01",
        "vc_descriptors": "Identifying emotions \\u00b7 Self-awareness \\u00b7 Personal vocabulary",
        "sc_1": "I can name a feeling using the feelings wheel.",
        "sc_2": "I can describe how that feeling feels in my body.",
        "sc_3": "I can think of one thing that helps me when I feel that way.",
        "cue_1": "Name it",
        "cue_2": "Feel it",
        "cue_3": "What helps?",
        "equipment_label": "RESOURCES",
        "equipment_1": "Feelings wheel (1 large for board, 1 per student)",
        "equipment_2": "Sticky notes (3 per student)",
        "equipment_3": "Picture cards (5 emotion faces)",
        "equipment_4": "Wellbeing journal (1 per student)",
        "equipment_5": "Calm-corner cushions (back of room)",
        "entry_1": "Enter, sit on carpet in circle.",
        "entry_2": "Hands on knees, kind face.",
        "entry_3": "Wait for chime before check-in.",
        "exit_1": "Wheel + sticky note to journal.",
        "exit_2": "Sit back in circle for share.",
        "exit_3": "Walk back to class teacher quietly.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 chime = stop, soft hands",
        "signal_2": "2 chimes = come to circle, kind face",
        "signal_practise": "Practise the chime x 3 at start. Show me kind face.",
        "phase_1": "1. CHECK-IN",
        "phase_2": "2. SKILL MODELLED",
        "phase_3": "3. PAIR PRACTICE",
        "phase_4": "4. APPLICATION SCENARIO",
        "phase_5": "5. REFLECTION CIRCLE",
        "phase_label_1": "CHECK-IN", "phase_label_2": "SKILL MODELLED (I do)",
        "phase_label_3": "PAIR PRACTICE (We do)", "phase_label_4": "SCENARIO (You do)",
        "phase_label_5": "REFLECTION CIRCLE",
        "p1_1": "Each student picks one emotion face card. Holds it up.",
        "p1_2": "Teacher names the emotion if student wants help.",
        "p1_3": "No \\u201Cwhy\\u201D today \\u2014 just name and notice.",
        "p1_say": "\\u201CFeelings are not good or bad \\u2014 they are messages. Today we learn to name them.\\u201D",
        "p2_1": "Show big feelings wheel. Centre = 6 main feelings, outer = words.",
        "p2_2": "Teacher tells a story (a small one) and lands on a feeling word.",
        "p2_3": "Demo: \\u201CMy hands felt tight. That\\u2019s frustrated.\\u201D",
        "p2_say_label": "Cue words: ",
        "p2_say": "Name it \\u00b7 Feel it \\u00b7 What helps?",
        "p3_1": "Pairs share one small feeling using the wheel.",
        "p3_2": "Listener nods \\u2014 no fixing, no judging.",
        "p3_3": "Swap. Praise specific kind listening.",
        "p3_say": "\\u201CName the feeling. Feel where it is. One thing that helps.\\u201D",
        "p4_1": "Card on the floor: \\u201CAt break, I missed catching the ball.\\u201D Pairs name a feeling.",
        "p4_2": "Write the feeling word on a sticky note. Stick it in your journal.",
        "p4_3": "Tier choice on what 2 helps strategies to add.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (point to wheel) \\u00b7 Core (write word + 1 helper) \\u00b7 Tier 3 (write feeling + 2 helpers + body sensation)",
        "p5_1": "Sit in circle. Place sticky note on the wheel (anonymous).",
        "p5_2": "Notice the cluster \\u2014 where do feelings land for our class?",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CFeelings are messages. Today you named them. Tomorrow we learn what helps each one.\\u201D",
        "behaviour_1": "Chime \\u2192 calmly name what you saw. Kind voice.",
        "behaviour_2": "Re-model the safe-space rule. Restart.",
        "behaviour_3": "Repeat \\u2192 calm corner cushion 1 min, then re-join.",
        "behaviour_4": "Big feelings? Calm corner is OK. Sit beside teacher.",
        "rescue_1": "Use picture cards instead of wheel words",
        "rescue_2": "Point to feeling instead of saying it",
        "rescue_3": "Adult shares first to model bravery",
        "ct_note_1": "Wellbeing journals stay in tray.",
        "ct_note_2": "Note any students who used calm corner.",
        "ct_note_3": "Confidentiality: only share concerns to class teacher 1:1.",
        "prior_1": "Term 1 covered happy / sad / angry / scared.",
        "prior_2": "Most can name 4-5 feelings.",
        "prior_3": "Some confuse feelings and behaviours \\u2014 this lesson clarifies.",
        "sequence_summary": "W1 (today) \\u00b7 W2 strategies for big feelings \\u00b7 W3 helping a friend \\u00b7 W4 our class agreement \\u00b7 W5 review",
        "resources_prepared": "Feelings wheels printed. Calm corner set up. Journals at tray.",
        "learning_intention": "We are learning to name a feeling using the feelings wheel and notice where it is in our body.",
        "why_this_matters": "Naming a feeling is the first step in regulating it. Year 1 is when emotional vocabulary takes off \\u2014 this lesson seeds 6 weeks of growth.",
        "vocab_tier1": "happy, sad, angry, scared, tired",
        "vocab_tier2": "feeling, calm, frustrated, proud, worried, surprised",
        "vocab_tier3": "regulation, sensation, message, awareness",
        "routine_1": "Same entry \\u2192 circle \\u2192 chime \\u2192 check-in every lesson.",
        "routine_2": "Predictable structure builds psychological safety.",
        "self_reg_1": "\\u201CWhere does this feeling live in your body?\\u201D",
        "self_reg_2": "\\u201CWhat helps when this feeling is big?\\u201D",
        "self_reg_3": "\\u201CCan you ask for help when you need it?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we name feelings using the wheel.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Show feelings wheel. Name 6 main feelings.",
        "teach_chunk_2": "Chunk 2 (3 min): Tell a small story \\u2014 land on \\u2018frustrated\\u2019. Name body sensation.",
        "teach_chunk_3": "Chunk 3 (4 min): Repeat with another story \\u2014 \\u2018proud\\u2019. Pick 2 students to model.",
        "worked_example": "(modelled exemplar: teacher tells a real-but-small story, points to feeling on wheel, points to body part where they felt it.)",
        "stem_1": "\\u201CI felt \\u2026 because \\u2026\\u201D",
        "stem_2": "\\u201CIt was in my \\u2026 (body part).\\u201D",
        "stem_3": "\\u201CWhat helped was \\u2026\\u201D",
        "cfu_1": "Show me a feeling face for: happy / worried / proud. Point to where it lives in your body.",
        "practice_stem_1": "\\u201CMy feeling lives in my \\u2026\\u201D",
        "practice_stem_2": "\\u201COne thing that helps me is \\u2026\\u201D",
        "cfu_2": "Mid-pair check: thumb-meter on feelings wheel \\u2014 do you see your feeling on it? If not, calm-corner.",
        "tier1_task_1": "Point to feeling on wheel (no words needed)",
        "tier1_task_2": "Use picture cards instead",
        "tier1_task_3": "Adult sits beside",
        "tier1_task_4": "1 helper strategy is enough",
        "core_task_1": "Name feeling using wheel words",
        "core_task_2": "Note body location",
        "core_task_3": "Write 1 helper strategy",
        "core_task_4": "Use cue words during pair share",
        "tier3_task_1": "Use 2-word feelings (e.g. \\u201Cfrustrated and proud\\u201D)",
        "tier3_task_2": "Write 2 helper strategies",
        "tier3_task_3": "Help a peer name their feeling",
        "tier3_task_4": "Identify the feeling under another feeling",
        "sc_1_short": "named a feeling",
        "sc_2_short": "where in body",
        "sc_3_short": "one helper",
        "metacog_1": "\\u201CWhich feeling is hardest to name? Why?\\u201D",
        "metacog_2": "\\u201CWhat happens when you name a feeling?\\u201D",
        "metacog_3": "\\u201CWho can you ask for help if a feeling is big?\\u201D",
        "retrieval_plan": "Use the feelings wheel at every Term 2 wellbeing check-in. Add 2 new words per week to wall.",
        "eald_1": "Translated wheel for home language", "eald_2": "Picture cards primary, words secondary", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Yarn circle for safe sharing", "koorie_2": "Connect to family wellbeing practices", "koorie_3": "Acknowledge community / family", "koorie_4": "Strength-based feedback",
        "disability_1": "Reduce sensory load (chime softer)", "disability_2": "Visual + tactile wheel", "disability_3": "Calm-corner break any time", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Wheel + journal provided", "disadv_2": "No-cost calm-corner cushions", "disadv_3": "Predictable rhythm = safety", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Charlie",
        "adjustment_eg": "Picture cards + adult close by",
        "support_eg": "EA sits beside; gentle prompts; calm-corner if needed",
        "lookfor_1": "Names a feeling using wheel words",
        "lookfor_2": "Identifies a body location for the feeling",
        "lookfor_3": "Names a strategy that helps",
        "misconception_1": "Confuses feeling with behaviour (\\u201Cangry = hit\\u201D) \\u2192 separate feeling from action",
        "misconception_2": "Says \\u2018good/bad\\u2019 instead of feeling \\u2192 redirect to wheel words",
        "misconception_3": "Avoids \\u2018big\\u2019 feelings \\u2192 normalise + offer calm corner",
    },

    "DigitalTech": {
        "year": "Year 6", "year_short": "Y6",
        "subject": "Digital Tech",
        "lesson_title": "Algorithms with branching: build a quiz in Scratch",
        "vc_codes": "VC2TDIK6P01 \\u00b7 VC2TDIK6P03 \\u00b7 VC2TDIK6P04",
        "vc_descriptors": "Algorithms \\u00b7 Branching \\u00b7 Conditionals \\u00b7 Iteration",
        "sc_1": "I can plan an algorithm using a flowchart with at least 1 branch.",
        "sc_2": "I can implement my algorithm in Scratch using if/else.",
        "sc_3": "I can test 2 inputs (correct + incorrect) and explain results.",
        "cue_1": "Plan, build, test",
        "cue_2": "If \\u2026 else \\u2026",
        "cue_3": "Test both paths",
        "equipment_label": "TOOLS / DEVICES",
        "equipment_1": "Laptops with Scratch (1 per pair)",
        "equipment_2": "Flowchart planning sheet",
        "equipment_3": "Pencil + eraser",
        "equipment_4": "Exemplar Scratch project loaded on board",
        "equipment_5": "Process journal",
        "entry_1": "Enter, sit at desks. Laptops closed.",
        "entry_2": "Hands on table. Wait for brief.",
        "entry_3": "No screens until \\u2018eyes-on-screen\\u2019 signal.",
        "exit_1": "Save Scratch project to class folder.",
        "exit_2": "Laptops shut, on charge cart.",
        "exit_3": "Process journal in tray.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 \\u2018eyes on screen\\u2019 = laptops down 45 degrees",
        "signal_2": "2 \\u2018eyes on screen\\u2019 = lids closed, hands flat",
        "signal_practise": "Practise the signal x 3 at start. Test response speed.",
        "phase_1": "1. BRIEF",
        "phase_2": "2. ITERATION PLAN",
        "phase_3": "3. BUILD / CODE",
        "phase_4": "4. TEST",
        "phase_5": "5. EVALUATE",
        "phase_label_1": "BRIEF", "phase_label_2": "ITERATION PLAN (I do)",
        "phase_label_3": "BUILD / CODE (We do)", "phase_label_4": "TEST (You do)",
        "phase_label_5": "EVALUATE",
        "p1_1": "\\u201CYour brief: build a quiz that asks ONE question and gives different feedback for right vs wrong.\\u201D",
        "p1_2": "Show exemplar Scratch project: working quiz with 1 branch.",
        "p1_3": "Identify the branching: \\u2018if answer = X then \\u2026 else \\u2026\\u2019",
        "p1_say": "\\u201CAlgorithms make decisions. Today\\u2019s decision: was the answer right?\\u201D",
        "p2_1": "On planning sheet, draw a flowchart: start \\u2192 ask \\u2192 if/else \\u2192 end.",
        "p2_2": "Demo non-example: no branch, just one feedback. Discuss.",
        "p2_3": "Show how flowchart maps to Scratch blocks.",
        "p2_say_label": "Cue words: ",
        "p2_say": "If \\u2026 else \\u2026 \\u00b7 Plan, build, test",
        "p3_1": "Open Scratch. Together build the \\u2018ask\\u2019 block.",
        "p3_2": "Add \\u2018if-else\\u2019 with one branch. Test it.",
        "p3_3": "Identify a bug together. Fix it. Praise specific debugging.",
        "p3_say": "\\u201CPlan first. Build small. Test both paths.\\u201D",
        "p4_1": "Pairs build their own quiz with 1 branch.",
        "p4_2": "Test 2 inputs: correct + incorrect. Note results in journal.",
        "p4_3": "Tier choice on extension features.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (1 question, 1 branch) \\u00b7 Core (2 questions, 1 branch each) \\u00b7 Tier 3 (3 questions, nested branches, score)",
        "p5_1": "Walk to 2 other pairs\\u2019 laptops. Test their quizzes.",
        "p5_2": "Share 1 thing that worked + 1 question for the maker.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CYou built an algorithm with a decision. Tomorrow we add loops.\\u201D",
        "behaviour_1": "Signal \\u2192 calmly name what you saw. Lids down.",
        "behaviour_2": "Re-model expectation. Restart task.",
        "behaviour_3": "Repeat \\u2192 sit out 1 min off-screen.",
        "behaviour_4": "Off-task on laptop? Lid closed. Sit beside teacher.",
        "rescue_1": "Use scaffolded Scratch starter project",
        "rescue_2": "1 question only \\u2014 no branch needed first",
        "rescue_3": "Pair with strong coder",
        "ct_note_1": "Projects saved to class folder.",
        "ct_note_2": "Note any laptops with issues to IT.",
        "ct_note_3": "Charge cart left on overnight.",
        "prior_1": "Term 1 covered sequences (no branching).",
        "prior_2": "Most can drag/drop Scratch blocks.",
        "prior_3": "Some don\\u2019t test their code \\u2014 emphasise testing today.",
        "sequence_summary": "W1 (today) \\u00b7 W2 add loops \\u00b7 W3 variables (score) \\u00b7 W4 user input validation \\u00b7 W5 finished quiz showcase",
        "resources_prepared": "Laptops charged. Scratch exemplar loaded. Class folder ready.",
        "learning_intention": "We are learning to design and code an algorithm with a decision (if/else branch).",
        "why_this_matters": "Branching is the foundation of every interactive program. Once students can plan and code an if/else, they can build games, quizzes, and simulations.",
        "vocab_tier1": "click, type, answer, screen, code",
        "vocab_tier2": "algorithm, branch, if, else, test, bug",
        "vocab_tier3": "conditional, iteration, debugging, flowchart, decomposition",
        "routine_1": "Same entry \\u2192 desks \\u2192 brief \\u2192 plan before build every lesson.",
        "routine_2": "No-screens-until-signal protects attention for the brief.",
        "self_reg_1": "\\u201CWhat will you do FIRST when your code doesn\\u2019t work?\\u201D",
        "self_reg_2": "\\u201CHow will you know your code is right \\u2014 testing or assuming?\\u201D",
        "self_reg_3": "\\u201CWhich path do you forget to test \\u2014 right or wrong answer?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we plan a flowchart, build it in Scratch, test both paths.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Show working exemplar. Identify the branch.",
        "teach_chunk_2": "Chunk 2 (3 min): Demo flowchart \\u2192 Scratch blocks mapping.",
        "teach_chunk_3": "Chunk 3 (4 min): Walk through ask + if/else block construction live.",
        "worked_example": "(modelled exemplar: completed flowchart side-by-side with Scratch project showing the if/else branch \\u2014 teacher\\u2019s screen on board.)",
        "stem_1": "\\u201CMy algorithm starts by \\u2026\\u201D",
        "stem_2": "\\u201CIf the user types \\u2026, then \\u2026 else \\u2026\\u201D",
        "stem_3": "\\u201CI tested with \\u2026 and got \\u2026\\u201D",
        "cfu_1": "\\u201CWhiteboards: write the if/else block in pseudocode for \\u2018is the answer 7?\\u2019\\u201D \\u00b7 \\u201CHands up if your flowchart has a branch.\\u201D",
        "practice_stem_1": "\\u201CMy code does \\u2026 when the user types \\u2026\\u201D",
        "practice_stem_2": "\\u201CMy bug was \\u2026 \\u2014 I fixed it by \\u2026\\u201D",
        "cfu_2": "Mid-build check: \\u201CHands up if both paths print different feedback. If not, fix that first.\\u201D",
        "tier1_task_1": "1 question, 1 branch",
        "tier1_task_2": "Use scaffolded starter project",
        "tier1_task_3": "Pair with strong coder",
        "tier1_task_4": "Verbal flow on whiteboard, code by adult",
        "core_task_1": "2 questions, each with 1 branch",
        "core_task_2": "Test both paths and journal results",
        "core_task_3": "Use cue words in journal",
        "core_task_4": "Save project to class folder",
        "tier3_task_1": "3+ questions, nested branches",
        "tier3_task_2": "Add a score variable",
        "tier3_task_3": "Add input validation (no blank answers)",
        "tier3_task_4": "Help a peer debug their if/else",
        "sc_1_short": "flowchart with branch",
        "sc_2_short": "if/else in Scratch",
        "sc_3_short": "tested both paths",
        "metacog_1": "\\u201CWhat happened when you only tested the right answer?\\u201D",
        "metacog_2": "\\u201CWhich was easier \\u2014 planning or coding? Why?\\u201D",
        "metacog_3": "\\u201CWhat would you do differently in your plan next time?\\u201D",
        "retrieval_plan": "Re-read flowchart conventions every Term 2 lesson. Re-test branching on a new brief W3 + W6.",
        "eald_1": "Visual flowchart symbols with translations", "eald_2": "Sentence frames for code talk", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Quiz topic relevant to community", "koorie_2": "Yarn circle for evaluation", "koorie_3": "Acknowledge family knowledge", "koorie_4": "Strength-based feedback",
        "disability_1": "Larger Scratch font / contrast", "disability_2": "Speech-to-text for typing", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Laptop provided by school", "disadv_2": "Scratch is free \\u2014 home access encouraged", "disadv_3": "Predictable rhythm", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Asha",
        "adjustment_eg": "Scaffolded starter project + speech-to-text",
        "support_eg": "EA helps drag blocks; student narrates logic",
        "lookfor_1": "Plans before building (flowchart present)",
        "lookfor_2": "Code includes if/else with two branches",
        "lookfor_3": "Tests at least 2 inputs and notes results",
        "misconception_1": "Tests only the right answer \\u2192 \\u201Ctest both paths\\u201D becomes a wall poster",
        "misconception_2": "Skips planning, jumps to code \\u2192 require flowchart before laptop opens",
        "misconception_3": "Confuses if/else with sequence \\u2192 demo two branches with different output",
    },

    "French": {
        "year": "Year 3", "year_short": "Y3",
        "subject": "French",
        "lesson_title": "Greetings: bonjour, ça va, comment tu t'appelles?",
        "vc_codes": "VC2LFL3C01 \\u00b7 VC2LFL3U01 \\u00b7 VC2LFL3M01",
        "vc_descriptors": "Greetings \\u00b7 Personal information \\u00b7 Spoken French \\u00b7 Cultural norms",
        "sc_1": "I can greet someone in French (Bonjour / Salut).",
        "sc_2": "I can ask and answer ça va? (how are you?).",
        "sc_3": "I can ask and answer comment tu t'appelles? (what's your name?).",
        "cue_1": "Bonjour",
        "cue_2": "Ça va?",
        "cue_3": "Je m'appelle…",
        "equipment_label": "RESOURCES",
        "equipment_1": "Mini French flag at front",
        "equipment_2": "Greeting flashcards (1 set per pair)",
        "equipment_3": "Audio: native-speaker greetings",
        "equipment_4": "Phrase wall: Bonjour, Salut, Ça va, Je m\\u2019appelle",
        "equipment_5": "French journal (1 per student)",
        "entry_1": "Enter with \\u201CBonjour Madame!\\u201D",
        "entry_2": "Sit at desks. Pencils ready.",
        "entry_3": "Wait for \\u201CBonjour la classe!\\u201D before responding.",
        "exit_1": "All say \\u201CAu revoir!\\u201D in chorus.",
        "exit_2": "Journal in tray.",
        "exit_3": "Walk back to class teacher \\u2014 use \\u201CSalut!\\u201D",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 clap = pencils down, eyes up",
        "signal_2": "2 claps = listen position, hands flat",
        "signal_practise": "Practise the signal x 3 at start. Match teacher\\u2019s voice volume.",
        "phase_1": "1. BONJOUR RITUAL",
        "phase_2": "2. VOCAB + DIALOGUE",
        "phase_3": "3. PAIR DIALOGUE",
        "phase_4": "4. MINI-CONVERSATION",
        "phase_5": "5. AU REVOIR + RECAP",
        "phase_label_1": "BONJOUR", "phase_label_2": "VOCAB + DIALOGUE (I do)",
        "phase_label_3": "PAIR DIALOGUE (We do)", "phase_label_4": "MINI-CONVERSATION (You do)",
        "phase_label_5": "AU REVOIR",
        "p1_1": "Teacher: \\u201CBonjour la classe!\\u201D Class: \\u201CBonjour Madame!\\u201D",
        "p1_2": "Echo Salut! and Bonjour! \\u2014 explore difference (formal vs informal).",
        "p1_3": "Each student names a country where French is spoken (cultural element).",
        "p1_say": "\\u201CIn France, greeting matters. Today we learn to say hello well.\\u201D",
        "p2_1": "Teach 4 phrases: Bonjour / Salut / Ça va? / Je m\\u2019appelle\\u2026",
        "p2_2": "Echo each 3x. Show non-example: silent entry. Discuss politeness.",
        "p2_3": "Demo a 4-line dialogue with a soft toy.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Bonjour \\u00b7 Ça va? \\u00b7 Je m\\u2019appelle\\u2026",
        "p3_1": "Pairs face each other. Practise the 4-line dialogue.",
        "p3_2": "Swap roles. Try once silently (mouth shape only) to focus pronunciation.",
        "p3_3": "Stop after 2 min. Pick 2 pairs to share. Praise specific pronunciation.",
        "p3_say": "\\u201CBonjour. Ça va? Je m\\u2019appelle\\u2026 Et toi?\\u201D",
        "p4_1": "Mingle: greet 4 different students using the dialogue.",
        "p4_2": "Tick a box on your journal for each name you learn.",
        "p4_3": "Tier choice on dialogue length.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (Bonjour + name) \\u00b7 Core (4-line dialogue) \\u00b7 Tier 3 (add ça va variations: bien / mal / comme ci comme ça)",
        "p5_1": "Sit. Au revoir chorus. Each student says one phrase they learned.",
        "p5_2": "Wave bye-bye, French style.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CAu revoir la classe! Tomorrow we add comment ça va: bien, mal, comme ci comme ça.\\u201D",
        "behaviour_1": "Clap signal \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model expectation in French. Restart.",
        "behaviour_3": "Repeat \\u2192 sit out 1 round, observe.",
        "behaviour_4": "Won\\u2019t speak French? Whisper version OK. No mocking allowed.",
        "rescue_1": "Phrase card on hand",
        "rescue_2": "Whisper version",
        "rescue_3": "Pair with strong speaker",
        "ct_note_1": "Phrase wall stays on \\u2014 next lesson reuses it.",
        "ct_note_2": "Note any students who avoided speaking.",
        "ct_note_3": "Roll stays with class teacher.",
        "prior_1": "Term 1 introduced French alphabet + numbers 1\\u201310.",
        "prior_2": "Most can pronounce vowels, some confuse \\u2018u\\u2019 sound.",
        "prior_3": "Some have French heritage \\u2014 invite to share, don\\u2019t single out.",
        "sequence_summary": "W1 (today) \\u00b7 W2 ça va variations \\u00b7 W3 introduce family words \\u00b7 W4 hobbies \\u00b7 W5 mini-presentation",
        "resources_prepared": "Flashcards laminated. Audio file queued. Phrase wall up.",
        "learning_intention": "We are learning to greet someone, ask how they are, and ask their name in French.",
        "why_this_matters": "Greetings are the social entry point in any language. With 4 phrases students can hold a polite micro-conversation \\u2014 huge motivation for early language learners.",
        "vocab_tier1": "hello, hi, name, how, you",
        "vocab_tier2": "Bonjour, Salut, Ça va, Je m\\u2019appelle, Comment",
        "vocab_tier3": "tu / vous (formal vs informal), francophone, pronunciation",
        "routine_1": "Same entry \\u2192 \\u201CBonjour la classe\\u201D \\u2192 desks every lesson.",
        "routine_2": "Repeated chorus builds pronunciation muscle memory.",
        "self_reg_1": "\\u201CHow will you ask if you don\\u2019t understand a French word?\\u201D",
        "self_reg_2": "\\u201CWhich phrase will you try first when you greet a new person?\\u201D",
        "self_reg_3": "\\u201CWhat helps you remember new sounds?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we greet, ask ça va, ask names.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Echo Bonjour x 3 + Salut x 3.",
        "teach_chunk_2": "Chunk 2 (3 min): Add Ça va? Echo + role-play with soft toy.",
        "teach_chunk_3": "Chunk 3 (4 min): Add Je m\\u2019appelle\\u2026 Demo full 4-line dialogue twice.",
        "worked_example": "(modelled exemplar: 4-line dialogue script on board with phonetic guide \\u2014 teacher demos with soft toy as partner.)",
        "stem_1": "\\u201CBonjour, je m\\u2019appelle \\u2026\\u201D",
        "stem_2": "\\u201CÇa va? Oui, ça va!\\u201D",
        "stem_3": "\\u201CEt toi, comment tu t\\u2019appelles?\\u201D",
        "cfu_1": "Whisper-only round: every student says \\u201CJe m\\u2019appelle [name]\\u201D once. \\u00b7 Thumbs if you can hold the dialogue.",
        "practice_stem_1": "\\u201CBonjour, je m\\u2019appelle \\u2026 Ça va?\\u201D",
        "practice_stem_2": "\\u201COui, ça va. Et toi?\\u201D",
        "cfu_2": "Mid-mingle check: tap shoulders \\u2014 \\u201Chands up if you used all 4 phrases at least once.\\u201D",
        "tier1_task_1": "Just \\u201CBonjour\\u201D + name",
        "tier1_task_2": "Phrase card on hand",
        "tier1_task_3": "Whisper version OK",
        "tier1_task_4": "Pair with strong speaker for mingle",
        "core_task_1": "Full 4-line dialogue",
        "core_task_2": "Greet 4 different classmates",
        "core_task_3": "Use cue phrases without card",
        "core_task_4": "Tick names learned in journal",
        "tier3_task_1": "Add bien / mal / comme ci comme ça",
        "tier3_task_2": "Switch tu vs vous appropriately",
        "tier3_task_3": "Greet teacher in French politely",
        "tier3_task_4": "Translate a peer\\u2019s English greeting",
        "sc_1_short": "Bonjour / Salut",
        "sc_2_short": "Ça va",
        "sc_3_short": "Je m\\u2019appelle",
        "metacog_1": "\\u201CWhich sound was hardest? Why?\\u201D",
        "metacog_2": "\\u201CHow did you remember the phrase order?\\u201D",
        "metacog_3": "\\u201CWhat would help you learn 5 new phrases tomorrow?\\u201D",
        "retrieval_plan": "Use Bonjour / Ça va / Je m\\u2019appelle every lesson entry. Re-test pronunciation W3 + W6.",
        "eald_1": "Phrase card with phonetic + L1 translation", "eald_2": "Sentence frames pre-shared", "eald_3": "Pair with French-speaking peer if available", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to multilingual identity / family", "koorie_2": "Yarn circle to share home greetings", "koorie_3": "Acknowledge family languages", "koorie_4": "Strength-based feedback",
        "disability_1": "Whisper version always OK", "disability_2": "Visual phrase card", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Phrase cards provided", "disadv_2": "Free audio resource for home practice", "disadv_3": "Predictable rhythm = safety", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Lila",
        "adjustment_eg": "Phrase card + whisper round",
        "support_eg": "EA models 1:1 first; student joins mingle round 3",
        "lookfor_1": "Pronounces Bonjour clearly (silent \\u2018r\\u2019)",
        "lookfor_2": "Holds 4-line dialogue without card",
        "lookfor_3": "Uses tu / vous appropriately for context",
        "misconception_1": "Mixes English in (\\u201CBonjour my name is\\u2026\\u201D) \\u2192 model whole-French dialogue again",
        "misconception_2": "Avoids the silent \\u2018r\\u2019 \\u2192 explicit pronunciation drill",
        "misconception_3": "Treats Salut as universal \\u2192 explain formal vs informal context",
    },

    "PerformingArts": {
        "year": "Year 4", "year_short": "Y4",
        "subject": "Performing Arts",
        "lesson_title": "Tableaux: telling a story in three frozen pictures",
        "vc_codes": "VC2ADRA4P01 \\u00b7 VC2ADRA4C01 \\u00b7 VC2ADRA4D01",
        "vc_descriptors": "Drama elements \\u00b7 Body \\u00b7 Space \\u00b7 Storytelling",
        "sc_1": "I can hold a still tableau for 5 seconds.",
        "sc_2": "I can show a story in 3 frozen pictures (beginning, middle, end).",
        "sc_3": "I can use facial expression and levels in my tableau.",
        "cue_1": "Freeze",
        "cue_2": "3 levels (high / mid / low)",
        "cue_3": "Story arc",
        "equipment_label": "COSTUMES / PROPS",
        "equipment_1": "Open performance space (push tables back)",
        "equipment_2": "Story prompt cards (1 per group of 4)",
        "equipment_3": "Tambourine (teacher signal)",
        "equipment_4": "Visual: tableau examples on board",
        "equipment_5": "Performance journal (1 per student)",
        "entry_1": "Enter quietly, sit on stage line.",
        "entry_2": "Bodies still. Eyes on teacher.",
        "entry_3": "Wait for tambourine before warm-up.",
        "exit_1": "Stand on stage line. Bow once.",
        "exit_2": "Walk to class teacher in 2 lines.",
        "exit_3": "Tables put back during clean-up minute.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 tambourine = freeze + breath",
        "signal_2": "2 tambourines = come to stage line",
        "signal_practise": "Practise the freeze x 3 at start. Show me a controlled freeze.",
        "phase_1": "1. BODY WARM-UP",
        "phase_2": "2. MODELLED REHEARSAL",
        "phase_3": "3. GROUP REHEARSAL",
        "phase_4": "4. PERFORMANCE",
        "phase_5": "5. REFLECT + APPLAUD",
        "phase_label_1": "WARM-UP", "phase_label_2": "MODELLED (I do)",
        "phase_label_3": "GROUP REHEARSAL (We do)", "phase_label_4": "PERFORMANCE (You do)",
        "phase_label_5": "REFLECT + APPLAUD",
        "p1_1": "Stretch + breath: arms up, exhale down x 3.",
        "p1_2": "Walk in space \\u2014 fill all corners. On freeze, hold for 5 sec.",
        "p1_3": "Pairs: mirror partner\\u2019s pose for 30 sec.",
        "p1_say": "\\u201CActors use bodies as their tools. Today we freeze stories into pictures.\\u201D",
        "p2_1": "Demo a tableau (\\u201CSeagull steals a chip\\u201D): 4 students freeze in pose.",
        "p2_2": "Show non-example: too still, no story. Then bad freeze (wobbling).",
        "p2_3": "Identify 3 levels (high / mid / low) and 1 facial expression.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Freeze \\u00b7 3 levels \\u00b7 Story arc",
        "p3_1": "Groups of 4 take a story prompt card.",
        "p3_2": "Build 3 tableaux: beginning, middle, end. 5 sec each.",
        "p3_3": "Stop. Pick 1 group to demo their middle frame. Praise levels.",
        "p3_say": "\\u201CFreeze. 3 levels. Story arc \\u2014 beginning, middle, end.\\u201D",
        "p4_1": "Each group performs all 3 tableaux with tambourine cue between.",
        "p4_2": "Audience watches in silence. Applaud after the third frame.",
        "p4_3": "Tier choice on extension features.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (1 frozen tableau) \\u00b7 Core (3 tableaux story arc) \\u00b7 Tier 3 (3 tableaux + transitions + sound)",
        "p5_1": "Sit on stage line. Each group says one thing they\\u2019re proud of.",
        "p5_2": "Audience names one tableau that told the story clearly.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CYou froze stories into pictures. Tomorrow we add movement between frames.\\u201D",
        "behaviour_1": "Tambourine \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model the safe-space rule. Restart.",
        "behaviour_3": "Repeat \\u2192 sit out 1 round, audience role.",
        "behaviour_4": "No-touch rule. If unsafe contact, full pause and reset.",
        "rescue_1": "1 tableau only \\u2014 still picture",
        "rescue_2": "Use a chair as anchor for low level",
        "rescue_3": "Pair with confident leader",
        "ct_note_1": "Tables back to setup before bell.",
        "ct_note_2": "Note any groups who couldn\\u2019t hold the freeze.",
        "ct_note_3": "Roll stays with class teacher.",
        "prior_1": "Term 1 covered space, body, voice.",
        "prior_2": "Most can hold a freeze for 3 sec.",
        "prior_3": "Some struggle with audience etiquette \\u2014 silence rule needs reinforcing.",
        "sequence_summary": "W1 (today) \\u00b7 W2 add transitions \\u00b7 W3 add voice \\u00b7 W4 character development \\u00b7 W5 short scene performance",
        "resources_prepared": "Performance space cleared. Story prompt cards laminated. Tambourine on teacher\\u2019s stool.",
        "learning_intention": "We are learning to use frozen pictures (tableaux) to tell a 3-part story.",
        "why_this_matters": "Tableaux build body-as-tool awareness, audience etiquette, and storytelling structure \\u2014 all foundational drama skills before voice and movement come in.",
        "vocab_tier1": "still, freeze, body, story, picture",
        "vocab_tier2": "tableau, level, expression, beginning, middle, end",
        "vocab_tier3": "ensemble, focus, intent, narrative arc, stillness",
        "routine_1": "Same entry \\u2192 stage line \\u2192 warm-up \\u2192 freeze every lesson.",
        "routine_2": "Predictable rituals build performance safety.",
        "self_reg_1": "\\u201CHow will you hold a freeze when your friend laughs?\\u201D",
        "self_reg_2": "\\u201CWhat will you focus on when you\\u2019re in the audience?\\u201D",
        "self_reg_3": "\\u201CIf your group disagrees, what\\u2019s your move?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we tell a 3-part story in frozen pictures.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Demo a single tableau with 3 levels.",
        "teach_chunk_2": "Chunk 2 (3 min): Non-example. Discuss what was missing.",
        "teach_chunk_3": "Chunk 3 (4 min): Demo 3 tableaux for one story arc.",
        "worked_example": "(modelled exemplar: 4 staff form a tableau \\u2014 photo or live demo on stage. Show high/mid/low levels and facial expression.)",
        "stem_1": "\\u201COur story is about \\u2026\\u201D",
        "stem_2": "\\u201COur 3 levels are \\u2026, \\u2026, \\u2026\\u201D",
        "stem_3": "\\u201CMy character feels \\u2026\\u201D",
        "cfu_1": "Hands up: how many levels in a strong tableau? Show me with bodies: high, mid, low.",
        "practice_stem_1": "\\u201COur first tableau showed \\u2026 because \\u2026\\u201D",
        "practice_stem_2": "\\u201CWe added \\u2026 to make our middle frame stronger.\\u201D",
        "cfu_2": "Mid-rehearsal freeze check: \\u201CHands up if all 3 levels are in your tableau. Adjust if not.\\u201D",
        "tier1_task_1": "1 tableau only \\u2014 a still picture",
        "tier1_task_2": "Stay seated, use upper-body only",
        "tier1_task_3": "Use a chair as low-level anchor",
        "tier1_task_4": "Verbal description if freeze is hard",
        "core_task_1": "3 tableaux \\u2014 beginning, middle, end",
        "core_task_2": "Use 3 levels in each frame",
        "core_task_3": "Hold each freeze 5 sec",
        "core_task_4": "1 facial expression per character",
        "tier3_task_1": "Add transitions (slow-mo) between frames",
        "tier3_task_2": "Add a single sound effect per frame",
        "tier3_task_3": "Have one frame told from a different perspective",
        "tier3_task_4": "Direct another group\\u2019s tableau",
        "sc_1_short": "5-sec freeze",
        "sc_2_short": "3 frames",
        "sc_3_short": "expression + levels",
        "metacog_1": "\\u201CWhich frame was hardest to hold? Why?\\u201D",
        "metacog_2": "\\u201CWhat did you notice in the audience that helped?\\u201D",
        "metacog_3": "\\u201CHow did your group decide on the story?\\u201D",
        "retrieval_plan": "Re-do a tableau warm-up at the start of every Term 2 drama lesson. Re-test storytelling W3 + W6.",
        "eald_1": "Story prompt with picture support", "eald_2": "Sentence frames pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to oral storytelling traditions", "koorie_2": "Yarn circle for reflection", "koorie_3": "Acknowledge community storytellers", "koorie_4": "Strength-based feedback",
        "disability_1": "Seated tableau OK", "disability_2": "Upper-body only acceptable", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "All resources provided in school", "disadv_2": "No costumes needed (body only)", "disadv_3": "Predictable rhythm", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Joseph",
        "adjustment_eg": "Seated tableau + upper-body only",
        "support_eg": "EA mirrors freeze beside; student leads on facial expression",
        "lookfor_1": "Holds the freeze without wobbling",
        "lookfor_2": "Includes 3 levels in tableau",
        "lookfor_3": "Story arc clear (beginning \\u2192 middle \\u2192 end)",
        "misconception_1": "Acts out story (movement) instead of freezing \\u2192 redo with strict 5-sec hold",
        "misconception_2": "All on one level \\u2192 visual reminder of 3-level rule",
        "misconception_3": "Audience talks during performance \\u2192 reset etiquette before performance phase",
    },

    "Science": {
        "year": "Year 5", "year_short": "Y5",
        "subject": "Science",
        "lesson_title": "States of matter: solid, liquid, gas",
        "vc_codes": "VC2SCH5C01 \\u00b7 VC2SCH5C02 \\u00b7 VC2SCH5S03",
        "vc_descriptors": "Chemical sciences \\u00b7 Particle theory \\u00b7 Reversible change",
        "sc_1": "I can sort 5 examples into solid, liquid, and gas.",
        "sc_2": "I can describe how particles move in each state.",
        "sc_3": "I can predict what happens when a state changes.",
        "cue_1": "Solid / liquid / gas",
        "cue_2": "Particles move",
        "cue_3": "Reversible change",
        "equipment_label": "MATERIALS",
        "equipment_1": "Ice cubes in tray (1 per group)",
        "equipment_2": "Water in jug",
        "equipment_3": "Balloon (sealed gas) per group",
        "equipment_4": "Sort cards (10 examples)",
        "equipment_5": "Lab journal (1 per student)",
        "entry_1": "Enter, sit at lab benches.",
        "entry_2": "Hands flat, materials at centre.",
        "entry_3": "Wait for safety brief before touching.",
        "exit_1": "Materials returned to tray.",
        "exit_2": "Hands washed.",
        "exit_3": "Lab journal in tray. Roll to class teacher.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 bell = hands off, eyes up",
        "signal_2": "2 bells = come to demo bench",
        "signal_practise": "Practise the signal x 3 at start. Match teacher\\u2019s pace.",
        "phase_1": "1. HOOK QUESTION",
        "phase_2": "2. EXPLICIT TEACHING",
        "phase_3": "3. GUIDED INVESTIGATION",
        "phase_4": "4. INDEPENDENT SORT",
        "phase_5": "5. SHARE STRATEGIES",
        "phase_label_1": "HOOK", "phase_label_2": "EXPLICIT TEACHING (I do)",
        "phase_label_3": "GUIDED INVESTIGATION (We do)", "phase_label_4": "INDEPENDENT SORT (You do)",
        "phase_label_5": "SHARE",
        "p1_1": "Show ice / water / steam (kettle). \\u201CWhat\\u2019s the same? Different?\\u201D",
        "p1_2": "Pairs whisper hypothesis on whiteboards.",
        "p1_3": "Share 2-3. Don\\u2019t correct \\u2014 say \\u201Clet\\u2019s investigate\\u201D.",
        "p1_say": "\\u201CScientists ask questions about what they see. Today\\u2019s question: how is matter arranged?\\u201D",
        "p2_1": "Define solid (fixed shape), liquid (takes container shape), gas (fills space).",
        "p2_2": "Draw particle diagram for each. Particles in solid: tight + ordered. Liquid: close + sliding. Gas: spread + fast.",
        "p2_3": "Show non-example: \\u201Cmist\\u201D \\u2014 is it gas or liquid? Discuss.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Solid \\u00b7 Liquid \\u00b7 Gas \\u00b7 Particles move",
        "p3_1": "Each group: observe ice cube melt for 5 min. Record temperature + state.",
        "p3_2": "Predict: what state will the puddle become if we leave it?",
        "p3_3": "Discuss reversible change. Praise specific observations.",
        "p3_say": "\\u201CSolid melts to liquid. Liquid evaporates to gas. Reversible change.\\u201D",
        "p4_1": "Sort 10 cards into S/L/G.",
        "p4_2": "Tier choice on extension.",
        "p4_3": "Teacher confers with 5 priority students.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (5 cards into S/L/G) \\u00b7 Core (10 cards + draw particle diagram for one) \\u00b7 Tier 3 (predict state changes for 3 examples)",
        "p5_1": "Pencils down. 2 students share their hardest sort.",
        "p5_2": "Thumbs up/middle/down for each SC.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CMatter has 3 states. Particles move differently in each. Tomorrow we explore plasma.\\u201D",
        "behaviour_1": "Signal \\u2192 calmly name what you saw. Hands off materials.",
        "behaviour_2": "Re-model expectation. Restart investigation.",
        "behaviour_3": "Repeat \\u2192 sit out 1 min, observation only.",
        "behaviour_4": "Mishandling materials? Materials away. Stand back.",
        "rescue_1": "Use simpler 5-card sort",
        "rescue_2": "Provide labelled diagram",
        "rescue_3": "Pair with strong observer",
        "ct_note_1": "Materials back to lab cupboard.",
        "ct_note_2": "Note any students who got <3/5 sorts right.",
        "ct_note_3": "Lab journals in tray.",
        "prior_1": "Term 1 covered properties of materials.",
        "prior_2": "Most know solid + liquid; gas less concrete.",
        "prior_3": "Some confuse melting with dissolving \\u2014 watch for this.",
        "sequence_summary": "W1 (today) \\u00b7 W2 changes of state with heat \\u00b7 W3 mass conservation \\u00b7 W4 mixtures \\u00b7 W5 mini-investigation",
        "resources_prepared": "Ice tray cleared. Sort cards laminated. Demo kettle safe.",
        "learning_intention": "We are learning to identify states of matter and how particles move in each.",
        "why_this_matters": "States of matter is the gateway to chemistry. Understanding particle behaviour underpins everything from cooking to climate change.",
        "vocab_tier1": "ice, water, steam, hot, cold",
        "vocab_tier2": "solid, liquid, gas, particle, state, melt",
        "vocab_tier3": "evaporation, condensation, sublimation, kinetic",
        "routine_1": "Same entry \\u2192 lab bench \\u2192 hands flat \\u2192 brief every lesson.",
        "routine_2": "Predictable safety routine = focus on science.",
        "self_reg_1": "\\u201CHow will you check if your sort is right?\\u201D",
        "self_reg_2": "\\u201CWhat\\u2019s your strategy when you\\u2019re unsure?\\u201D",
        "self_reg_3": "\\u201CWhy might 2 scientists disagree on a sort?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we sort matter into solid, liquid, gas \\u2014 and explain why.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Define each state. Use ice/water/steam as anchor.",
        "teach_chunk_2": "Chunk 2 (3 min): Draw particle diagram for each. Discuss arrangement + motion.",
        "teach_chunk_3": "Chunk 3 (4 min): Non-example \\u2014 mist. Class discussion.",
        "worked_example": "(modelled exemplar: 3-state particle diagram on board with ice/water/steam beside it. Teacher annotates particle motion.)",
        "stem_1": "\\u201CThis is a [state] because particles \\u2026\\u201D",
        "stem_2": "\\u201CWhen heated, this will \\u2026\\u201D",
        "stem_3": "\\u201CI predict \\u2026 because \\u2026\\u201D",
        "cfu_1": "Whiteboards: draw particles in a solid. \\u00b7 Hands up: gas or liquid \\u2014 milk?",
        "practice_stem_1": "\\u201CMy sort says \\u2026 because particles \\u2026\\u201D",
        "practice_stem_2": "\\u201CMy partner saw \\u2026 \\u2014 I\\u2019d add \\u2026\\u201D",
        "cfu_2": "Mid-investigation freeze: \\u201CWhiteboards \\u2014 what state is your ice now?\\u201D Adjust based on responses.",
        "tier1_task_1": "5-card sort only",
        "tier1_task_2": "Labels provided on cards",
        "tier1_task_3": "Adult close by for verbal sort",
        "tier1_task_4": "Use diagram instead of writing",
        "core_task_1": "10-card sort (S/L/G)",
        "core_task_2": "Draw particle diagram for 1 example",
        "core_task_3": "Use cue words in journal",
        "core_task_4": "Note 1 misconception you avoided",
        "tier3_task_1": "Predict state changes for 3 examples (heated/cooled)",
        "tier3_task_2": "Sort 3 \\u2018trickies\\u2019 (jelly, fog, smoke)",
        "tier3_task_3": "Explain why mass stays the same on state change",
        "tier3_task_4": "Design a quick test to identify an unknown state",
        "sc_1_short": "sort S/L/G",
        "sc_2_short": "particle motion",
        "sc_3_short": "predict change",
        "metacog_1": "\\u201CWhich card was trickiest? What helped you decide?\\u201D",
        "metacog_2": "\\u201CWhat\\u2019s the difference between melting and dissolving?\\u201D",
        "metacog_3": "\\u201CHow did the particle diagram help you?\\u201D",
        "retrieval_plan": "Return to particle motion in every Term 2 science lesson. Re-test sort W3 + W6.",
        "eald_1": "Bilingual sort cards", "eald_2": "Sentence stems pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to materials in country (water cycle on river)", "koorie_2": "Yarn circle for share-back", "koorie_3": "Acknowledge community knowledge", "koorie_4": "Strength-based feedback",
        "disability_1": "Reduce sensory load (no kettle for some)", "disability_2": "Magnified sort cards", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "All materials provided", "disadv_2": "No-cost ice / water demo", "disadv_3": "Predictable rhythm", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Hugo",
        "adjustment_eg": "5-card sort + labelled diagram",
        "support_eg": "EA reads cards aloud; student matches with stickers",
        "lookfor_1": "Sorts 4/5 cards correctly",
        "lookfor_2": "Particle diagram shows correct arrangement + motion",
        "lookfor_3": "Predicts state change with reasoning",
        "misconception_1": "Confuses melting with dissolving \\u2192 contrast ice melt vs sugar dissolve",
        "misconception_2": "Thinks gas is \\u2018nothing\\u2019 \\u2192 balloon proves gas has mass",
        "misconception_3": "Particles \\u2018rest\\u2019 in solid \\u2192 demo: solid particles vibrate, never still",
    },
}
