"""Per-subject content configs for v11 lesson templates.
Each config defines the strings to substitute into build_v11_example.js (PE base).
"""

# Each subject config — these become Year X Term 2 Week 1 lessons
SUBJECTS = {
    "Numeracy": {
        "year": "Year 3", "year_short": "Y3",
        "subject": "Numeracy",
        "lesson_title": "Adding 2-digit numbers using bridging through 10",
        "vc_codes": "VC2M3N03 \\u00b7 VC2M3N04 \\u00b7 VC2M3N06",
        "vc_descriptors": "Number \\u00b7 Place value \\u00b7 Mental strategies \\u00b7 Multi-step problems",
        "sc_1": "I can add 2-digit numbers using bridging through 10.",
        "sc_2": "I can record my strategy clearly with numbers and a number line.",
        "sc_3": "I can check my answer using a different strategy.",
        "cue_1": "Bridge to 10",
        "cue_2": "Tens + ones",
        "cue_3": "Check it",
        "equipment_label": "MATERIALS",
        "equipment_1": "Whiteboards + markers (1 per pair)",
        "equipment_2": "MAB blocks (tens + ones, 1 set per pair)",
        "equipment_3": "Number line strip (0\\u2013100, laminated)",
        "equipment_4": "Place value chart on board",
        "equipment_5": "Exit ticket sheet (1 per student)",
        "entry_1": "Enter, sit at desks. Whiteboards out.",
        "entry_2": "Pencils down, eyes up.",
        "entry_3": "Wait for silence before number talk.",
        "exit_1": "Whiteboards to bin. MAB to tray.",
        "exit_2": "Exit ticket on teacher\\u2019s desk on the way out.",
        "exit_3": "Roll stays with class teacher.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 bell = pencils down, eyes up",
        "signal_2": "2 bells = whiteboards on knee, listen",
        "signal_practise": "Practise the signal x 3 at start. Match teacher\\u2019s pace.",
        "phase_1": "1. NUMBER TALK",
        "phase_2": "2. WORKED EXAMPLE",
        "phase_3": "3. GUIDED PRACTICE",
        "phase_4": "4. INDEPENDENT PROBLEM",
        "phase_5": "5. SHARE STRATEGIES",
        "phase_label_1": "NUMBER TALK", "phase_label_2": "WORKED EXAMPLE (I do)",
        "phase_label_3": "GUIDED PRACTICE (We do)", "phase_label_4": "INDEPENDENT PROBLEM (You do)",
        "phase_label_5": "SHARE STRATEGIES",
        "p1_1": "Show 28 + 7. Pairs whisper a strategy on whiteboards.",
        "p1_2": "Choose 2 students to share. Annotate strategies on board.",
        "p1_3": "Highlight bridging through 10 if it appears. If not, model it.",
        "p1_say": "\\u201CMathematicians use strategies. Today\\u2019s strategy: bridging through 10.\\u201D",
        "p2_1": "Demo 47 + 26. Step 1: split 26 into 3 + 23 (so 47 + 3 = 50). Step 2: 50 + 23 = 73.",
        "p2_2": "Show NON-example: lining up + carrying without place-value language. Discuss.",
        "p2_3": "Repeat with 38 + 25 \\u2014 think aloud the bridge.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Bridge to 10 \\u00b7 Tens + ones \\u00b7 Check it",
        "p3_1": "Together: 56 + 28. Pairs talk first, share strategy. Teacher scribes.",
        "p3_2": "Try 39 + 47. Stop midway \\u2014 \\u201Cwhat\\u2019s our bridge?\\u201D Adjust.",
        "p3_3": "Praise specific strategy choices by name.",
        "p3_say": "\\u201CBridge to 10. Tens + ones. Check it.\\u201D",
        "p4_1": "Solve 4 problems on the worksheet. Show your strategy with a number line.",
        "p4_2": "Tier 1 / Core / Tier 3 (see page 3).",
        "p4_3": "Teacher confers with 5 priority students.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (single-digit + 2-digit) \\u00b7 Core (2-digit + 2-digit no carry beyond 100) \\u00b7 Tier 3 (3-step with checking)",
        "p5_1": "Pencils down. 2 students share their strategy on the board.",
        "p5_2": "Thumbs up/middle/down for each SC.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CYou used bridging through 10 today. Tomorrow we add 3-digit numbers using the same idea.\\u201D",
        "behaviour_1": "Signal \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model expectation. Restart problem.",
        "behaviour_3": "Repeat \\u2192 sit out 1 min, re-join.",
        "behaviour_4": "Refusing to write? Verbalise + adult scribes.",
        "rescue_1": "Reduce to 1 problem with MAB blocks shown",
        "rescue_2": "Provide a worked example card",
        "rescue_3": "Pair with strong peer for talk-aloud",
        "ct_note_1": "Leave sheet on classroom teacher\\u2019s desk.",
        "ct_note_2": "Note any students who got <2/4 on exit ticket.",
        "ct_note_3": "Whiteboards + MAB returned to maths corner.",
        "prior_1": "Term 1 covered 2-digit + 1-digit no regrouping.",
        "prior_2": "Most can add to 100 with concrete supports.",
        "prior_3": "Some still rely on counting on \\u2014 need bridging strategy.",
        "sequence_summary": "W1 (today) \\u00b7 W2 same with subtraction \\u00b7 W3 3-digit + 2-digit \\u00b7 W4 word problems \\u00b7 W5 mixed review",
        "resources_prepared": "MAB sets at each table. Worksheet printed + differentiated by tier. Number line strip on each desk.",
        "learning_intention": "We are learning to add 2-digit numbers using bridging through 10.",
        "why_this_matters": "Bridging through 10 is a foundational mental-strategy that scales to all multi-digit addition. Without it, students rely on slow counting or rote algorithms with no understanding.",
        "vocab_tier1": "add, take, count, more, less",
        "vocab_tier2": "sum, equals, regroup, bridge, jump, strategy",
        "vocab_tier3": "place value, partition, decompose, commutative property",
        "routine_1": "Same entry \\u2192 desks \\u2192 whiteboards \\u2192 number talk every lesson.",
        "routine_2": "Predictable structure reduces cognitive load (4 Elements of Learning \\u2014 attention).",
        "self_reg_1": "\\u201CWhich number is closer to a tens number? Use that one to bridge.\\u201D",
        "self_reg_2": "\\u201CHow will you check if your answer is reasonable?\\u201D",
        "self_reg_3": "\\u201CWhat will you try if your first strategy doesn\\u2019t work?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words on board. \\u201CToday we use the bridge-to-10 strategy to add 2-digit numbers.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Demo 47 + 26 \\u2014 split 26 into 3 + 23, so 47 + 3 = 50, then 50 + 23 = 73.",
        "teach_chunk_2": "Chunk 2 (3 min): Show non-example without place-value language. Ask \\u201Cwhat\\u2019s missing?\\u201D",
        "teach_chunk_3": "Chunk 3 (4 min): Repeat with 38 + 25, then 56 + 27. Pick 2 students to demo their bridge.",
        "worked_example": "(modelled exemplar: 47 + 26 = 73 with number-line jumps drawn — teacher annotates each step. Photo of board.)",
        "stem_1": "\\u201CI bridged at \\u2026 because \\u2026\\u201D",
        "stem_2": "\\u201CMy tens are \\u2026 and my ones are \\u2026\\u201D",
        "stem_3": "\\u201CI checked by \\u2026\\u201D",
        "cfu_1": "\\u201CWhiteboards: show me how you\\u2019d split 26 to bridge to 10 from 47.\\u201D \\u00b7 \\u201CThumbs if you\\u2019re ready.\\u201D",
        "practice_stem_1": "\\u201CI bridged at \\u2026 because that gets me to a tens number.\\u201D",
        "practice_stem_2": "\\u201CMy strategy was \\u2026 and I checked by \\u2026\\u201D",
        "cfu_2": "Mid-practice freeze: \\u201CWhiteboards \\u2014 show me your bridge for 39 + 47.\\u201D Adjust based on responses.",
        "tier1_task_1": "1-digit + 2-digit (e.g. 8 + 24)",
        "tier1_task_2": "MAB blocks visible at desk",
        "tier1_task_3": "Worked example card on hand",
        "tier1_task_4": "Verbal answers OK \\u2014 adult scribes",
        "core_task_1": "4 problems: 2-digit + 2-digit, sums under 100",
        "core_task_2": "Show strategy with number line",
        "core_task_3": "Check at least one with a different method",
        "core_task_4": "Stuck? Use cue words on the board.",
        "tier3_task_1": "Sums over 100 (e.g. 67 + 58)",
        "tier3_task_2": "Word problems requiring 2 steps",
        "tier3_task_3": "Find an error in a peer\\u2019s work and explain the fix",
        "tier3_task_4": "Write your own bridging problem for the class",
        "sc_1_short": "bridging through 10",
        "sc_2_short": "showing my strategy",
        "sc_3_short": "checking with a different way",
        "metacog_1": "\\u201CWhich part was hardest \\u2014 the bridge or the check?\\u201D",
        "metacog_2": "\\u201CWhat made bridging easier today than counting on?\\u201D",
        "metacog_3": "\\u201CWhich cue did you say in your head as you worked?\\u201D",
        "retrieval_plan": "Return to bridging through 10 in every Term 2 lesson. Re-test on exit ticket W3 + W6.",
        "eald_1": "Number cards + visual on desk", "eald_2": "Sentence frames pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to family counting / yarning", "koorie_2": "Yarn circle for share-back", "koorie_3": "Acknowledge family knowledge", "koorie_4": "Strength-based feedback",
        "disability_1": "Reduce visual clutter on board", "disability_2": "Scribed by adult / typed", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Whiteboard + pencil provided", "disadv_2": "No-cost manipulatives", "disadv_3": "Predictable rhythm = safety", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Tariq",
        "adjustment_eg": "MAB blocks + worked-example card",
        "support_eg": "Adult scribes for first 2 problems; checks at midway",
        "lookfor_1": "Bridges through 10 explicitly named",
        "lookfor_2": "Records strategy on number line",
        "lookfor_3": "Uses \\u2018check it\\u2019 cue (different method)",
        "misconception_1": "Stuck in counting-on \\u2192 model 2 bridges side-by-side; show speed difference",
        "misconception_2": "Splits incorrectly (e.g. 26 \\u2192 5 + 21) \\u2192 ask \\u201Cwhat takes 47 to a tens number?\\u201D",
        "misconception_3": "Doesn\\u2019t check \\u2192 add \\u201Ccheck it\\u201D as a 4th cue word",
    },

    "VisualArt": {
        "year": "Year 4", "year_short": "Y4",
        "subject": "Visual Art",
        "lesson_title": "Texture: making rubbings + repeating pattern",
        "vc_codes": "VC2AVA4P01 \\u00b7 VC2AVA4C01 \\u00b7 VC2AVA4D01",
        "vc_descriptors": "Visual conventions \\u00b7 Texture \\u00b7 Pattern \\u00b7 Visual artists\\u2019 work",
        "sc_1": "I can make a rubbing that shows clear texture.",
        "sc_2": "I can choose 3 textures to make a repeating pattern.",
        "sc_3": "I can describe my pattern using texture words.",
        "cue_1": "Press, pull",
        "cue_2": "Repeat",
        "cue_3": "Rough / smooth / bumpy",
        "equipment_label": "MATERIALS",
        "equipment_1": "Wax crayons (peeled, 3 colours, 1 per student)",
        "equipment_2": "A4 paper (2 sheets per student)",
        "equipment_3": "Texture rubbing items (leaves, coins, mesh, sandpaper) at each table",
        "equipment_4": "Exemplar artist image: Max Ernst frottage (on board)",
        "equipment_5": "Process journal (1 per student)",
        "entry_1": "Enter, sit at art tables.",
        "entry_2": "Materials in centre. Hands flat on desk.",
        "entry_3": "Wait for silence before technique demo.",
        "exit_1": "Crayons + items returned to caddy.",
        "exit_2": "Rubbings to drying rack with name corner.",
        "exit_3": "Tables wiped, journal stacked.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 bell = tools down, eyes up",
        "signal_2": "2 bells = come to gallery wall",
        "signal_practise": "Practise the signal x 3 at start.",
        "phase_1": "1. HOOK / INSPIRATION",
        "phase_2": "2. TECHNIQUE DEMO",
        "phase_3": "3. GUIDED PRACTICE",
        "phase_4": "4. INDEPENDENT MAKING",
        "phase_5": "5. GALLERY WALK",
        "phase_label_1": "HOOK", "phase_label_2": "TECHNIQUE DEMO (I do)",
        "phase_label_3": "GUIDED PRACTICE (We do)", "phase_label_4": "INDEPENDENT MAKING (You do)",
        "phase_label_5": "GALLERY WALK",
        "p1_1": "Show Max Ernst frottage. \\u201CWhat do you notice?\\u201D Pairs share.",
        "p1_2": "Pass round 3 mystery objects in a bag. Feel \\u2014 don\\u2019t look. Describe.",
        "p1_3": "Build a class word bank: rough, smooth, bumpy, ridged, soft.",
        "p1_say": "\\u201CTexture is what we feel. Today we capture it on paper.\\u201D",
        "p2_1": "Demo: place leaf under paper. Lay crayon flat. Press + pull strokes.",
        "p2_2": "Show non-example: pressing too hard \\u2192 paper rips. Discuss.",
        "p2_3": "Demo repeating pattern: same texture x 3 across the page.",
        "p2_say_label": "Cue words: ",
        "p2_say": "Press \\u00b7 pull \\u00b7 repeat",
        "p3_1": "All students try one rubbing of the leaf. Stop after 2 min.",
        "p3_2": "Share what works. Adjust technique with one re-demo.",
        "p3_3": "Try a second texture. Praise specific strokes by name.",
        "p3_say": "\\u201CPress, pull, repeat. Show me a clear texture.\\u201D",
        "p4_1": "Choose 3 textures from the table caddy.",
        "p4_2": "Make a repeating pattern: ABC ABC ABC across your A4.",
        "p4_3": "Add 1 texture word label per stripe in your process journal.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (1 texture, ABA) \\u00b7 Core (3 textures, ABCABC) \\u00b7 Tier 3 (own arrangement + colour)",
        "p5_1": "Tools down. Walk gallery in silence with notepad.",
        "p5_2": "Star one piece you admire + write one texture word for it.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CYou captured texture on paper. Tomorrow we add colour blending.\\u201D",
        "behaviour_1": "Signal \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model the expectation. Restart making.",
        "behaviour_3": "Repeat \\u2192 sit out 1 min, observe gallery.",
        "behaviour_4": "Won\\u2019t engage? Offer caddy-monitor or word-bank scribe role.",
        "rescue_1": "Bigger items (less precision needed)",
        "rescue_2": "Hand-over-hand for first stroke",
        "rescue_3": "1 texture only \\u2014 success first",
        "ct_note_1": "Rubbings drying \\u2014 collect tomorrow.",
        "ct_note_2": "Note any students who finished early / struggled.",
        "ct_note_3": "Crayons + items back in caddy.",
        "prior_1": "Term 1 covered line + shape.",
        "prior_2": "Most know primary colours and can name a texture.",
        "prior_3": "Some have not used wax crayons flat \\u2014 need re-demo.",
        "sequence_summary": "W1 (today) \\u00b7 W2 add colour blending \\u00b7 W3 mixed media collage \\u00b7 W4 self-portrait with texture \\u00b7 W5 gallery exhibition",
        "resources_prepared": "Crayons peeled before class. Texture caddy at each of 6 tables. Ernst image on screen.",
        "learning_intention": "We are learning to use rubbing as a technique to capture texture and build a repeating pattern.",
        "why_this_matters": "Texture is one of the visual elements artists use to express ideas. Pattern teaches sequencing and visual rhythm \\u2014 skills that scale into design and craft for life.",
        "vocab_tier1": "rough, smooth, bumpy, soft, hard",
        "vocab_tier2": "texture, pattern, repeat, rubbing, frottage",
        "vocab_tier3": "frottage, surface, relief, motif, sequence",
        "routine_1": "Same entry \\u2192 art table \\u2192 hands flat \\u2192 demo every lesson.",
        "routine_2": "Predictable structure protects making time (cognitive load attention).",
        "self_reg_1": "\\u201CIf your texture is faint, what should you change \\u2014 pressure or angle?\\u201D",
        "self_reg_2": "\\u201CHow will you decide which textures repeat well together?\\u201D",
        "self_reg_3": "\\u201CWhat texture word will you try on for the gallery?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words on board. \\u201CToday we use rubbing to make a clear texture, then build a repeating pattern.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Demo a leaf rubbing \\u2014 crayon flat, press + pull strokes.",
        "teach_chunk_2": "Chunk 2 (3 min): Non-example (too hard). Ask \\u201Cwhat went wrong?\\u201D",
        "teach_chunk_3": "Chunk 3 (4 min): Demo ABC pattern with 3 textures across the page.",
        "worked_example": "(modelled exemplar: leaf-coin-mesh repeating pattern strip — teacher\\u2019s sample on display.)",
        "stem_1": "\\u201CMy texture is \\u2026 because I felt \\u2026\\u201D",
        "stem_2": "\\u201CI repeated \\u2026 to make a pattern.\\u201D",
        "stem_3": "\\u201CI changed \\u2026 because \\u2026\\u201D",
        "cfu_1": "\\u201CHands up: which is texture and which is colour?\\u201D \\u00b7 \\u201CShow me the \\u2018press + pull\\u2019 motion in the air.\\u201D",
        "practice_stem_1": "\\u201CMy first texture worked because \\u2026\\u201D",
        "practice_stem_2": "\\u201CMy partner used \\u2026 differently \\u2014 next time I\\u2019ll try \\u2026\\u201D",
        "cfu_2": "Mid-make freeze: \\u201CHold up your rubbing \\u2014 thumb up if your texture is clear, middle if faint, down if needs re-demo.\\u201D",
        "tier1_task_1": "1 texture only, ABA pattern (3 stripes)",
        "tier1_task_2": "Hand-over-hand for first stroke",
        "tier1_task_3": "Use chunky crayon with grip aid",
        "tier1_task_4": "Verbal pattern description (no labels)",
        "core_task_1": "3 textures, ABCABC repeating",
        "core_task_2": "1 texture word per stripe in journal",
        "core_task_3": "Choose 1 colour combo with intent",
        "core_task_4": "Title your work",
        "tier3_task_1": "Choose own arrangement (e.g. AABCABC, ABA)",
        "tier3_task_2": "Add a 4th texture as accent",
        "tier3_task_3": "Write a 2-sentence artist statement",
        "tier3_task_4": "Lead a peer through the rubbing technique",
        "sc_1_short": "clear texture",
        "sc_2_short": "3 textures repeating",
        "sc_3_short": "texture words",
        "metacog_1": "\\u201CWhich texture surprised you the most?\\u201D",
        "metacog_2": "\\u201CWhat did you change halfway through, and why?\\u201D",
        "metacog_3": "\\u201CWhich cue word was hardest to remember?\\u201D",
        "retrieval_plan": "Return to texture words in every Term 2 art lesson. Add 1 new texture word per lesson to wall.",
        "eald_1": "Texture word card with photo", "eald_2": "Sentence frames pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Connect to country textures (bark, river stone)", "koorie_2": "Yarn circle for share-back", "koorie_3": "Acknowledge family / community textures", "koorie_4": "Strength-based feedback",
        "disability_1": "Chunky crayon + grip aid", "disability_2": "Tactile texture board to choose from", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Crayons + paper provided \\u2014 no own kit", "disadv_2": "Caddy items found in school grounds", "disadv_3": "Predictable rhythm = safety", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Mia",
        "adjustment_eg": "Chunky crayon + 1 texture only",
        "support_eg": "EA hand-over-hand for first stroke; checks at midway",
        "lookfor_1": "Crayon flat \\u2014 not gripped like a pencil",
        "lookfor_2": "Press + pull motion (not scribbling)",
        "lookfor_3": "3 textures present in repeating pattern",
        "misconception_1": "Crayon held like pencil \\u2192 demo \\u2018crayon on its side\\u2019 again",
        "misconception_2": "Pressing too hard \\u2192 ripped paper. Demo light pull.",
        "misconception_3": "Random textures (no pattern) \\u2192 add ABCABC scaffold strip",
    },

    "HASS": {
        "year": "Year 5", "year_short": "Y5",
        "subject": "HASS",
        "lesson_title": "Reading sources from the Victorian gold rush",
        "vc_codes": "VC2HH5K01 \\u00b7 VC2HH5K02 \\u00b7 VC2HH5S03",
        "vc_descriptors": "History \\u00b7 Sources \\u00b7 Causation \\u00b7 Continuity and change",
        "sc_1": "I can identify primary vs secondary sources.",
        "sc_2": "I can extract 2 facts from a source.",
        "sc_3": "I can ask 1 question the source doesn\\u2019t answer.",
        "cue_1": "Who?",
        "cue_2": "When?",
        "cue_3": "What\\u2019s missing?",
        "equipment_label": "RESOURCES",
        "equipment_1": "Source pack: 2 photos + 1 letter + 1 diary excerpt (1 per pair)",
        "equipment_2": "Source analysis worksheet (1 per student)",
        "equipment_3": "Wall map of Victoria 1850s",
        "equipment_4": "Word wall: primary, secondary, source, evidence",
        "equipment_5": "Inquiry journal (1 per student)",
        "entry_1": "Enter, sit at desks. Pencils ready.",
        "entry_2": "Source packs face-down at each table.",
        "entry_3": "Wait for silence before big question.",
        "exit_1": "Sources back in pack envelope.",
        "exit_2": "Worksheet to teacher\\u2019s tray on the way out.",
        "exit_3": "Journal stacked, roll to class teacher.",
        "signal_label": "ATTENTION SIGNAL",
        "signal_1": "1 bell = pencils down, eyes up",
        "signal_2": "2 bells = come to map",
        "signal_practise": "Practise the signal x 3 at start.",
        "phase_1": "1. BIG QUESTION",
        "phase_2": "2. SOURCE INTRO",
        "phase_3": "3. SOURCE ANALYSIS",
        "phase_4": "4. RECORDING / JOURNAL",
        "phase_5": "5. DISCUSSION",
        "phase_label_1": "BIG QUESTION", "phase_label_2": "SOURCE INTRO (I do)",
        "phase_label_3": "SOURCE ANALYSIS (We do)", "phase_label_4": "RECORD (You do)",
        "phase_label_5": "DISCUSSION",
        "p1_1": "Display: \\u201CWhy did 90,000 people come to Victoria in 1852?\\u201D",
        "p1_2": "Pairs whisper one hypothesis on whiteboards.",
        "p1_3": "Share 2-3. Don\\u2019t correct \\u2014 say \\u201Clet\\u2019s use sources to check\\u201D.",
        "p1_say": "\\u201CHistorians use sources \\u2014 evidence from the past \\u2014 to answer big questions.\\u201D",
        "p2_1": "Define primary (made at the time) vs secondary (made later).",
        "p2_2": "Show photo + letter as primary; textbook entry as secondary.",
        "p2_3": "Model 3 questions on a source: Who? When? What\\u2019s missing?",
        "p2_say_label": "Cue words: ",
        "p2_say": "Who? \\u00b7 When? \\u00b7 What\\u2019s missing?",
        "p3_1": "Pairs open source pack. Read 1 source together.",
        "p3_2": "Annotate: who made it, when, 2 facts.",
        "p3_3": "Stop after 5 min. Share 1 fact and 1 question.",
        "p3_say": "\\u201CWho? When? What\\u2019s missing? Two facts. One question.\\u201D",
        "p4_1": "On worksheet, identify each source as primary or secondary.",
        "p4_2": "Extract 2 facts from each. Write 1 question per source.",
        "p4_3": "Teacher confers with 5 priority students.",
        "p4_summary_label": "Tier choice: ",
        "p4_summary": "Tier 1 (1 source, scaffold) \\u00b7 Core (all 4 sources) \\u00b7 Tier 3 (compare 2 sources)",
        "p5_1": "Pencils down. Sit on map mat.",
        "p5_2": "3 students share a question their source didn\\u2019t answer.",
        "p5_say_label": "Exit line: ",
        "p5_say": "\\u201CHistorians ask the questions sources don\\u2019t answer. Tomorrow we hunt for those answers.\\u201D",
        "behaviour_1": "Signal \\u2192 calmly name what you saw.",
        "behaviour_2": "Re-model expectation. Restart analysis.",
        "behaviour_3": "Repeat \\u2192 sit out 1 min, re-join with map work.",
        "behaviour_4": "Refusing to write? Offer reader role + adult scribes.",
        "rescue_1": "1 source only \\u2014 simplest one (photo)",
        "rescue_2": "Provide annotated example",
        "rescue_3": "Pair with confident reader",
        "ct_note_1": "Sources stay with HASS \\u2014 to office cupboard.",
        "ct_note_2": "Worksheets to assess fact-extraction tonight.",
        "ct_note_3": "Roll stays with class teacher.",
        "prior_1": "Term 1 covered Indigenous Australians pre-1788.",
        "prior_2": "Most can name a fact and a question.",
        "prior_3": "Primary vs secondary is new \\u2014 needs strong modelling.",
        "sequence_summary": "W1 (today) \\u00b7 W2 perspectives + bias \\u00b7 W3 cause and effect \\u00b7 W4 timeline build \\u00b7 W5 mini-essay",
        "resources_prepared": "Source packs at each table. Map on wall. Word wall updated.",
        "learning_intention": "We are learning to read historical sources to extract facts and ask questions.",
        "why_this_matters": "Historians don\\u2019t just memorise facts \\u2014 they question evidence. This skill underpins critical thinking across every subject.",
        "vocab_tier1": "old, new, before, after, then",
        "vocab_tier2": "source, evidence, fact, question, history",
        "vocab_tier3": "primary, secondary, perspective, bias, causation",
        "routine_1": "Same entry \\u2192 desks \\u2192 source pack \\u2192 big question every lesson.",
        "routine_2": "Predictable structure reduces cognitive load.",
        "self_reg_1": "\\u201CHow will you know if a source is reliable?\\u201D",
        "self_reg_2": "\\u201CWhat\\u2019s the difference between a fact and an opinion?\\u201D",
        "self_reg_3": "\\u201CWhat will you do if your source contradicts your hypothesis?\\u201D",
        "focus_the_learning": "State LI + SC. Show cue words. \\u201CToday we use sources to ask questions about the gold rush.\\u201D",
        "teach_chunk_1": "Chunk 1 (3 min): Define primary vs secondary with examples.",
        "teach_chunk_2": "Chunk 2 (3 min): Model 3 source-questions on a photo.",
        "teach_chunk_3": "Chunk 3 (4 min): Show what \\u2018facts\\u2019 vs \\u2018questions\\u2019 look like in writing.",
        "worked_example": "(modelled exemplar: annotated photo with Who/When/Missing labels and 2 facts circled \\u2014 teacher\\u2019s exemplar pinned to board.)",
        "stem_1": "\\u201CThis source is primary because \\u2026\\u201D",
        "stem_2": "\\u201CTwo facts I know: \\u2026 and \\u2026\\u201D",
        "stem_3": "\\u201CMy source doesn\\u2019t tell me \\u2026\\u201D",
        "cfu_1": "\\u201CHands up: is this letter from 1852 primary or secondary?\\u201D \\u00b7 \\u201CWhiteboards: write 1 word for \\u2018evidence from the past\\u2019.\\u201D",
        "practice_stem_1": "\\u201CMy source says \\u2026 because \\u2026\\u201D",
        "practice_stem_2": "\\u201CMy partner found \\u2026 \\u2014 I noticed \\u2026\\u201D",
        "cfu_2": "Mid-analysis check: \\u201CWhiteboards \\u2014 write the year your source was made.\\u201D Adjust if students can\\u2019t locate dates.",
        "tier1_task_1": "1 source (photo with caption)",
        "tier1_task_2": "Annotated example provided",
        "tier1_task_3": "Verbal answers OK \\u2014 adult scribes",
        "tier1_task_4": "Word wall vocabulary at desk",
        "core_task_1": "All 4 sources analysed",
        "core_task_2": "2 facts + 1 question per source",
        "core_task_3": "Use cue words in your writing",
        "core_task_4": "Mark each as primary or secondary",
        "tier3_task_1": "Compare 2 sources \\u2014 what differs?",
        "tier3_task_2": "Identify possible bias in 1 source",
        "tier3_task_3": "Write a paragraph using all 4 sources",
        "tier3_task_4": "Suggest a source you wish you had",
        "sc_1_short": "primary vs secondary",
        "sc_2_short": "2 facts",
        "sc_3_short": "1 question",
        "metacog_1": "\\u201CWhich source did you trust most? Why?\\u201D",
        "metacog_2": "\\u201CWhat would you ask if you could go back and meet the writer?\\u201D",
        "metacog_3": "\\u201CWhich cue helped you most \\u2014 Who, When, or What\\u2019s missing?\\u201D",
        "retrieval_plan": "Return to primary vs secondary in every Term 2 HASS lesson. Re-test on a new source W3 + W6.",
        "eald_1": "Visual source supported by translation", "eald_2": "Sentence frames pre-shared", "eald_3": "Pair with bilingual peer", "eald_4": "Demonstrate, don\\u2019t only describe",
        "koorie_1": "Acknowledge Country (Wadawurrung gold-rush impact)", "koorie_2": "Yarn circle for discussion", "koorie_3": "Note absence of Aboriginal voice in colonial sources", "koorie_4": "Strength-based feedback",
        "disability_1": "Large-print sources available", "disability_2": "Audio recording of letter", "disability_3": "Movement break option", "disability_4": "ISP / IEP adjustments applied",
        "disadv_1": "Sources + worksheet provided", "disadv_2": "No-cost field trip alternative (virtual tour)", "disadv_3": "Predictable rhythm", "disadv_4": "Strength noticed and named",
        "student_name_eg": "(eg) Aria",
        "adjustment_eg": "Annotated exemplar + simplified source",
        "support_eg": "EA reads source aloud; student annotates with stickers",
        "lookfor_1": "Identifies primary vs secondary correctly",
        "lookfor_2": "Extracts 2 verifiable facts (not opinions)",
        "lookfor_3": "Asks a genuine question (not a yes/no)",
        "misconception_1": "Confuses opinion with fact \\u2192 ask \\u201Cwho would dispute that?\\u201D",
        "misconception_2": "Treats textbook as primary \\u2192 timeline back to source date",
        "misconception_3": "Doesn\\u2019t question gaps \\u2192 model \\u201CI wonder \\u2026\\u201D stem",
    },
}
